bot_token:5409981479:AAFxVTxUWr8agluiGqIKD7kzd6KYyvGKmY8
#telegraph_token:
#telegraph_account:
#telegraph_author_name:
#telegraph_author_url:
#socks5:
update_interval: 1
user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

mysql:
  host:
  port:
  user:
  password:
  database:

telegram:
  endpoint:

log:
  level: release
  db_log: false # 打印数据库日志，false则只会打印数据库错误日志

#  file: ./flowerss.log

sqlite:
  path: ./data.db

allowed_users:
- 1454043499
- -1001696027685
- -1001358645122
- 1246582899

message_mode: md
message_tpl: /mirror {{.RawLink}}
